---
- name: PostgreSQL | Add PostgreSQL repository apt-key
  apt_key:
    id: ACCC4CF8
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: PostgreSQL | Add PostgreSQL repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main'
    state: present

- name: Download barman (debian)
  apt: pkg=barman state=present update_cache=yes
  when: ansible_os_family == "Debian"
  tags: packages

- name: Download barman (redhat)
  yum: pkg=barman state=present update_cache=yes
  when: ansible_os_family == "RedHat"
  tags: packages
