---
- name: Set WAL level
  lineinfile:
    dest: {{ postgres_configuration_file_path }}
    regexp: wal_level
    line: "wal_level = 'archive'"
  tags: configuration

- name: Activate archive mode
  lineinfile:
    dest: {{ postgres_configuration_file_path }}
    regexp: archive_mode
    line: "archive_mode = on"
  tags: configuration

- name: Set archive command
  lineinfile:
    dest: {{ postgres_configuration_file_path }}
    regexp: archive_command
    line: "archive_command = 'rsync -a %p {{ barman_user }}@{{ barman_hostname }}:/var/lib/barman/main/incoming/%f'"
  tags: configuration
